SkyJSTranslationsLoaded({
    "btn_get_started" : "开始",
    "btn_ok" : "确定",
    "btn_close" : "关闭",
    "btn_continue" : "继续",
    "lnk_start_call" : "开始通话",
    "lnk_learn_more" : "了解有关Skype的更多信息",
    "lnk_learn_more_about_outlook" : "了解关于Skype for Outlook.com的更多信息",
    "lnk_learn_more_about_account_merging" : "了解帐户合并详情",
    "lnk_get_skype" : "下载Skype",
    "msg_setup_info_in_title" : "{INVITER} 想要与您进行免费的Skype通话。",
    "msg_setup_info_in" : "请下载Skype插件，完成一次性快速设置，以便我们为您接通。",
    "msg_setup_info_out" : "您需要下载Skype插件并完成一次性快速设置，才能呼叫{INVITER}。",
    "msg_setting_up_info" : "您已开始下载。 请按照提示保存和运行Skype插件。",
    "msg_just_a_moment" : "请稍候...",
    "msg_click_save_file" : "单击\u201C保存文件\u201D",
    "msg_run_downloaded_file" : "运行下载的文件",
    "msg_ready_to_start_calling" : "准备好开始进行通话",
    "msg_download_too_long" : "如果下载中断或耗时太长，您可以{LINK_RESTART_MANUALLY}手动重新开始下载{LINK_END}，或立即下载{LINK_GET_SKYPE_APP}完整版Skype应用程序{LINK_END}。",
    "msg_setup_complete" : "设置完成。 您已经准备好开始与{INVITER}通话",
    "msg_setup_complete_call_inviter" : "设置完成。 您现在即可呼叫{INVITER}。",
    "msg_enjoy_skype_call" : "享受您与{INVITER}的Skype通话",
    "msg_invite_expired" : "很抱歉，此通话链接已过期。",
    "msg_ask_for_link" : "如果您想要新链接，则请求{INVITER}再次呼叫您。 或下载Skype，以便您随时免费呼叫他们。",
    "msg_cookies_disabled" : "Cookie被禁用",
    "msg_cookies_disabled_ext" : "您的浏览器未启用Cookie。 请更改安全选项中的适当设置以继续。",
    "msg_install_plugin_outlook" : "请安装Skype插件，以设置通过Outlook.com进行通话",
    "msg_install_plugin_and_call_from_outlook" : "请安装Skype插件，以设置通过Outlook.com进行通话。",
    "msg_play_video" : "播放视频",
    "msg_wrong_user" : "您使用了一个不同的帐户登录",
    "msg_wrong_user_text" : "您收到了一个通话邀请，但您现在登录的Microsoft帐户与本通话邀请所发送的帐户不同。 要进行此次通话，您可以下载Skype或使用其他Microsoft帐户登录。",
    "ttl_skype_calling_setup" : "Skype通话设置",
    "lnk_tou_agree" : "我同意 － 继续",
    "lnk_tou_disagree" : "现在不用，谢谢",
    "msg_voice_and_video" : "免费的语音和视频通话",
    "msg_easily_ims" : "即使在通话时也可发送即时消息",
    "msg_call_your_buddies" : "呼叫您所有的Messenger联系人",
    "msg_bring_skype_contacts" : "将Skype联系人加入Outlook.com",
    "msg_before_we_start" : "开始使用之前\u2026",
    "msg_you_must_agree" : "您必须同意{LINK_TERMS}Skype使用条款{LINK_END}和{LINK_PRIVACY}Skype隐私权政策{LINK_END}。",
    "msg_before_we_start_you_must_agree" : "必须同意{LINK_TERMS}Skype使用条款{LINK_END}和{LINK_PRIVACY}Skype隐私权政策{LINK_END}才能开始使用Skype",
    "msg_inform_me_about_new_products" : "通过电子邮件通知我关于新产品、功能和特别优惠的消息。",
    "msg_would_you_like_to_merge" : "您愿意合并Skype和Microsoft帐户，以便在Outlook.com中查看Skype联系人吗？",
    "msg_skype_account_to_merge" : "请输入您的Skype帐户详细信息",
    "alt_back" : "返回",
    "plh_skype_name" : "Skype用户名",
    "plh_password" : "密码",
    "val_sign_in" : "登录",
    "lnk_problems_signing_in" : "登录时遇到问题？",
    "msg_reach_your_skype_contacts_in_outlook_and_call" : "现在，您可以在Outlook.com中联系您的Skype和Messenger联系人。",
    "msg_can_not_connect_to_skype_server" : "很抱歉，无法连接Skype服务器。 请稍后重试。",
    "ttl_age_limit" : "很抱歉，您不符合年龄限制条件",
    "txt_age_limit" : "您无法使用此Microsoft帐户登录Skype，因为您没有达到您所在国家\/地区规定的年龄。",
    "ttl_problem_signing_in" : "登录时出现问题",
    "msg_problem_signing_in" : "您尝试登录时失败的次数太多。 请稍后重试。",
    "ttl_not_signed_in" : "您尚未登录live.com",
    "msg_not_signed_in" : "您目前尚未登录live.com。 请登录后重试。",
    "lnk_cancel_and_change_account" : "取消并更改帐户",
    "msg_check_your_details" : "很抱歉，这些信息无效。 请检查您的详细信息。",
    "msg_setup_is_complete_ready_to_calling" : "设置完成。 您已准备好开始通话。",
    "msg_how_to_make_a_call" : "如何拨打电话",
    "msg_click_on_chat_icon" : "点击右上角的聊天图标",
    "msg_select_person_to_call" : "选择您要呼叫的人",
    "msg_click_on_video_or_voice_call_buttons" : "点击视频或语音通话按钮",
    "msg_need_more_help" : "需要更多帮助？",
    "lnk_watch_this_video" : "观看此视频",
    "msg_accounts_is_already_merged" : "帐户已合并",
    "msg_account_is_already_merged" : "Skype帐户{SKYPE_ACCOUNT}已与其他Microsoft帐户合并。",
    "msg_what_you_can_do" : "您可以：",
    "msg_use_existing_merged_skype_account" : "使用其他Microsoft帐户登录Outlook.com。",
    "msg_merge_your_accounts" : "最后一步 － 合并您的帐户",
    "msg_merge_this_microsoft_account" : "{LINK_MERGE}将此Microsoft帐户{LINK_END}与不同的Skype帐户合并。",
    "msg_create_a_brand_new_skype_account" : "{LINK_NEW_ACCOUNT}创建新Skype帐户{LINK_END}（如有需要，您可以将其合并至该Microsoft帐户）。",
    "lnk_get_more_help_with_account_merging" : "获取有关帐户合并的更多帮助",
    "btn_i_have_skype_account" : "我有Skype帐户",
    "btn_new_to_skype" : "没有，我是Skype新用户",
    "msg_generic_error" : "发生了错误",
    "msg_generic_error_text" : "Skype for Outlook.com现在似乎不可用。 请稍后重试或立即下载完整版Skype应用程序。",
    "msg_rollback" : "发生了错误。 Skype for Outlook.com现在似乎不可用。 请稍后重试或立即下载完整版Skype应用程序。",
    "btn_download_skype" : "下载Skype",
    "ttl_metro_plugin_not_supported" : "从商店下载Skype",
    "msg_metro_plugin_not_supported" : "您使用的IE浏览器版本目前暂不支持Skype for Outlook.com插件。 但不用担心，我们在商店中为您提供了一款快速美观的全新Skype。 而且完全免费。",
    "msg_metro_plugin_not_supported_winrt" : "您使用的Windows系统版本目前暂不支持Skype for Outlook.com插件。 但不用担心，我们在商店中为您提供了一款快速美观的全新Skype。 而且完全免费。",
    "msg_skype_for_metro" : "很抱歉，Skype for Outlook.com尚不支持该浏览器。 请下载最新版Skype for Windows 8，享受最佳体验。",
    "btn_get_skype_for_metro" : "获取Skype for Windows RT",
    "ttl_skype_plugin_update" : "您的Skype插件需要更新",
    "msg_skype_plugin_update" : "要进行此次Skype通话，您需要更新为最新版本。",
    "btn_update_plugin" : "更新插件",
    "ttl_after_instalation_continue" : "安装完成后请点击\u201C继续\u201D",
    "ttl_heres_what_todo_next" : "接下来请进行以下操作：",
    "msg_select_run" : "选择\u201C运行\u201D",
    "msg_your_skype_plugin_installs" : "安装您的Skype插件",
    "msg_thats_it_start_calling" : "安装完毕 － 开始通话",
    "ttl_your_skype_is_downloading" : "正在下载Skype插件。 请稍候...",
    "ttl_plugin_download_error" : "无法下载Skype for Outlook.com插件",
    "txt_ie10_window8_error" : "Internet Explorer 10 for Windows 8目前暂不支持此插件。 但您可以从Windows商店下载完整版Skype应用程序。",
    "msg_reinstall_outgoing" : "要呼叫{INVITER}，您需要更新您的Skype插件。 这不会花费很长时间。",
    "msg_reinstall_incoming" : "要接听来自{INVITER}的电话，您需要先更新您的Skype插件。 这不会花费很长时间。",
    "ttl_pluginInstall" : "您已开始下载。 下一步是什么？",
    "msg_pluginInstall_msie_step1" : "下载完成后，请运行Skype插件安装程序。",
    "msg_pluginInstall_msie_step2" : "单击\u201C是\u201D以接受\u201C用户帐户控制\u201D设置。",
    "msg_pluginInstall_chrome_win_step1" : "运行浏览器左下方的Skype插件安装程序。",
    "msg_pluginInstall_chrome_win_step2" : "单击\u201C是\u201D以接受\u201C用户帐户控制\u201D设置。",
    "msg_pluginInstall_firefox_win_step1" : "在弹出提示时单击\u201C保存文件\u201D。",
    "msg_pluginInstall_firefox_win_step2" : "在下载窗口中双击\u201CSkypeWebPlugin.msi\u201D。",
    "msg_pluginInstall_safari_step1" : "Skype插件将被下载到您的计算机。",
    "msg_pluginInstall_safari_step2" : "运行下载的文件并按照说明进行操作。",
    "msg_pluginInstall_step3" : "通话准备就绪。",
    "msg_setup_info_preview_title" : "欢迎。 立即预览Skype。",
    "msg_skype_call" : "Skype通话",
    "msg_plugin_not_installed_yet" : "您似乎还未安装该插件。 请按照说明进行安装。",
    "btn_next" : "下一步",
    "msg_select_next_after_plugin_is_installed" : "安装该插件后选择\u201C下一步\u201D。",
    "btn_let_get_started" : "开始使用",
    "msg_plugin_download_started" : "您已开始下载。",
    "msg_select_next" : "安装该插件后选择\u201C下一步\u201D。",
    "btn_toast_answer_video" : "开始视频通话",
    "btn_toast_answer_audio" : "开始语音通话",
    "btn_toast_decline" : "拒绝接听来电"
});